### ISSUE TITLE
Implement Admin-Dashboard / Product List View (1d)

### ISSUE THREAD

**Issue by chzellweger** [monobasic/CAS-FEE-PROJEKT-2#49]

**Comment by monobasic** [comment]
- If logged in as Admin, show edit/delete buttons for each product in list and detail view
- Edit link points to: /admin/edit/:id
- Delete points to confirmation message (toastr, or js) then deletes product
- "Add Product" Link to Toolbar Account Dropdown
- Don't show image, if its not uploaded
