### ISSUE TITLE
Unit Tests - (2d)

### ISSUE THREAD

**Issue by monobasic** [monobasic/CAS-FEE-PROJEKT-2#60]

**Comment by monobasic** [comment]
@chzellweger finally got the Jasmine stuff working.. needed to update zone.js to a specific fixed version. Also karma port:9999 seems to work on my machine instead of using the default port.
(jest would work as well, I tried it but confused "translating" the two APIs in my head)

**Comment by chzellweger** [comment]
now we have tests for four domains that make more or less sense. close or not?
