### ISSUE TITLE
Carousel breaks on slide & click

### ISSUE THREAD

**Issue by chzellweger** [monobasic/CAS-FEE-PROJEKT-2#90]
To reproduce: Try sliding carousel-items around, then try clicking the arrow-buttons.
Throws error: `"ERROR TypeError: Cannot read property 'currentSlide' of null"`

Also: On slide, white position-indicator-circles don't change.

**Comment by monobasic** [comment]
I am aware of this, it's a problem of the carousel third party dependency, which doesn't handle swipe event correctly. Will be most probably out of scope to fix the library..
