### ISSUE TITLE
fix repeated occurrences of authService.user.subscribe

### ISSUE THREAD

**Issue by chzellweger** [monobasic/CAS-FEE-PROJEKT-2#91]
The pattern

```
this.authService.user.subscribe(user => {
  this.user = user;
});
```
shows up all over the code to store a reference to the current user in various components. In most cases, this is used to trigger certain authorization based features in templates which could be simplified by introducing a "CurrentUser" service with methods like ".hasRole(...)" that returns an observable based on the underlying AuthService.user behavior subject. Those returned observables can then be combined with the "async" pipe in the template which would probably eliminate most of the duplicate code.

**Comment by monobasic** [comment]
out of scope. I just realize we use auth / user in very different kinds.. sometimes props from user are needed in the template, sometimes we do stuff depending on the auth state and so on..
